docs: add acta for 2021-08-21
open-source-uc/actas pull request #12
Opened 2021-08-21 22:44 UTC by agucova

2021-08-22 02:25 UTC, benjavicente requested changes

2021-08-22 02:25 UTC, benjavicente commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
Le añadiría una categoría aparte a estos ítems, ahora están bajo `## Proyectos`

2021-08-22 02:25 UTC, benjavicente commented on 2021/2021-08-21.md
> +Se pide actualizar osuc.dev y awesome-uc para agregar auto-ramos.
Esto va para los otros proyectos también (ramos-uc, busca-salas, etc).

2021-08-22 02:25 UTC, benjavicente commented on 2021/2021-08-21.md
> +Se necesita ayuda también con hacer la página una PWA y el manejo de la ubicación. (los detalles estan en las issues)
Typo mío, el punto tiene que estar luego del paréntesis.

El salto de línea entre las oraciones no es consistente con el resto del documento, pero eso no es un problema.

2021-08-22 02:25 UTC, benjavicente commented on 2021/2021-08-21.md
> +@agucova y @Dyotson están manejando el lado técnico con una web en Docusaurus + React y se necesitan manos en tanto el lado técnico como en contenido (tips del campus, servicios de la u, todo tipo de
```diff
#                    vvvvvvvv                         vvvvvv
- se necesitan manos en tanto el lado técnico como en contenido
+ se necesitan manos tanto en el lado técnico como en el del contenido
```

2021-08-22 19:32 UTC, agucova commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
No sé si esto es un punto adicional. Esto se conversó en la reu?

2021-08-22 19:34 UTC, benjavicente commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
En la tabla que propuse están bajo la categoría `## Otros`

2021-08-22 19:51 UTC, agucova commented
Todo resuelto.

2021-08-22 19:57 UTC, benjavicente commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
@agucova  me refiero a los 3 ítems / puntos **de la acta**, los que estoy comentando.

2021-08-22 20:57 UTC, agucova commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
jajajaja ctm yo entendiendo nada

2021-08-22 21:00 UTC, benjavicente commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
```md.diff
+ ## Otros

  ### Cambio de hora de las reuniones [@benjavicente]
  Queda pendiente revisar la hora semanal con un Doodle.

  ### Eventos Presenciales
  Se discute que por restricciones del campus no es aún viable.

  ### Canales de proyectos opt-out en vez de opt-in en Discord [@benjavicente]
  Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
```

2021-08-23 00:41 UTC, FarDust requested changes

2021-08-23 00:41 UTC, FarDust commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out. Se propone moverlos de categoría.
Quedamos en que no se moverían de categoría sino que se modificarían los roles para poder ver los proyectos por defecto.

2021-08-23 12:40 UTC, benjavicente commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
El cambio que sugiero es este:
```diff
+ ##  Otros

  ### Cambio de hora de las reuniones [@benjavicente]
  Queda pendiente revisar la hora semanal con un Doodle.

  ### Eventos Presenciales
  Se discute que por restricciones del campus no es aún viable.

  ### Canales de proyectos opt-out en vez de opt-in en Discord [@benjavicente]
  Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
```

2021-08-23 12:40 UTC, benjavicente commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out. Se propone moverlos de categoría.
En el último commit hubo una confusión [discutida aquí](https://github.com/open-source-uc/actas/pull/12#discussion_r693549188).

2021-08-23 16:23 UTC, FarDust commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out. Se propone moverlos de categoría.
Ya pero aun no esta modificado

2021-08-23 17:34 UTC, agucova commented on 2021/2021-08-21.md
> +Hay acuerdo en cambiar el defecto con respecto a la visibilidad de canales de proyectos de opt-in a opt-out.
Ahora si

2021-08-23 17:36 UTC, agucova commented
@benjavicente @FarDust Ahora ahora si

2021-08-23 17:39 UTC, benjavicente approved these changes

2021-08-23 18:05 UTC, FarDust approved these changes

2021-08-23 18:47 UTC, merged