Create 2021-05-29.md
open-source-uc/actas pull request #7
Opened 2021-05-29 23:41 UTC by benjavicente

Revisen faltas de ortografías plz

2021-05-29 23:44 UTC, FarDust approved these changes

2021-05-30 01:11 UTC, agucova requested changes

2021-05-30 01:11 UTC, agucova commented on 2021/2021-05-29.md
> +- Que es: comindad que desarrolla software en conjunto.
Qué* es: comunidad*

2021-05-30 01:11 UTC, agucova commented on 2021/2021-05-29.md
> +Miemrbo de GitHub: aquellos que son miembros activos (criterio de reuniones, desafio inicial, y aportes a proyectos).
Miembro*, desafío*

2021-05-30 01:11 UTC, agucova commented on 2021/2021-05-29.md
> +Se ordenara Discord a medida que cresca la organización.
ordenará*

2021-06-01 00:24 UTC, agucova approved these changes

2021-06-01 00:25 UTC, merged